// @generated by protoc-gen-es v1.8.0
// @generated from file user/v1/user.proto (package admiral.user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message admiral.user.v1.GetUserRequest
 */
export const GetUserRequest = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.user.v1.GetUserRequest",
  [],
);

/**
 * @generated from message admiral.user.v1.GetUserResponse
 */
export const GetUserResponse = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.user.v1.GetUserResponse",
  () => [
    { no: 1, name: "foo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

