version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cli"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/ui/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
