snapshot:
  name_template: "{{ incpatch .Version }}-dev"

report_sizes: true

before:
  hooks:
    - make ui

builds:
  - id: datalift
    binary: datalift
    dir: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version=$(VERSION)"
  - id: datalift-migrate
    main: ./cmd/migrate
    binary: datalift-migrate
    dir: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version=$(VERSION)"

  - id: datalift-server
    binary: datalift-server
    dir: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      pre:
        - cmd: go -C server run cmd/assets/generate.go ../ui/build
          output: true
    flags:
      - -tags=withAssets -trimpath
    ldflags:
      - -s -w -X main.version=$(VERSION)"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else if and (eq .Os "darwin" ) (eq .Arch "all") }}ubin
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

sboms:
  - artifacts: archive

release:
  footer: |
    **Full Changelog**: https://github.com/DataliftHQ/datalift/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Helping out

    This release is only possible thanks to **all** the support of some **awesome people**!