// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: session/v1/session.proto

package sessionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SessionAPI_GetSession_FullMethodName = "/admiral.session.v1.SessionAPI/GetSession"
)

// SessionAPIClient is the client API for SessionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionAPIClient interface {
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
}

type sessionAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionAPIClient(cc grpc.ClientConnInterface) SessionAPIClient {
	return &sessionAPIClient{cc}
}

func (c *sessionAPIClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, SessionAPI_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionAPIServer is the server API for SessionAPI service.
// All implementations should embed UnimplementedSessionAPIServer
// for forward compatibility
type SessionAPIServer interface {
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
}

// UnimplementedSessionAPIServer should be embedded to have forward compatible implementations.
type UnimplementedSessionAPIServer struct {
}

func (UnimplementedSessionAPIServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}

// UnsafeSessionAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionAPIServer will
// result in compilation errors.
type UnsafeSessionAPIServer interface {
	mustEmbedUnimplementedSessionAPIServer()
}

func RegisterSessionAPIServer(s grpc.ServiceRegistrar, srv SessionAPIServer) {
	s.RegisterService(&SessionAPI_ServiceDesc, srv)
}

func _SessionAPI_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionAPIServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionAPI_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionAPIServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionAPI_ServiceDesc is the grpc.ServiceDesc for SessionAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.session.v1.SessionAPI",
	HandlerType: (*SessionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSession",
			Handler:    _SessionAPI_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session/v1/session.proto",
}
