// @generated by protoc-gen-es v1.8.0
// @generated from file settings/v1/settings.proto (package admiral.settings.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message admiral.settings.v1.OIDCConfig
 */
export const OIDCConfig = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.settings.v1.OIDCConfig",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "issuer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cli_client_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "scopes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message admiral.settings.v1.SettingsRequest
 */
export const SettingsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.settings.v1.SettingsRequest",
  [],
);

/**
 * @generated from message admiral.settings.v1.SettingsResponse
 */
export const SettingsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.settings.v1.SettingsResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "oidc_config", kind: "message", T: OIDCConfig },
  ],
);

