// @generated by protoc-gen-es v1.8.0
// @generated from file settings/v1/settings.proto (package admiral.settings.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message admiral.settings.v1.OIDCConfig
 */
export declare class OIDCConfig extends Message<OIDCConfig> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string issuer = 2;
   */
  issuer: string;

  /**
   * @generated from field: string client_id = 3;
   */
  clientId: string;

  /**
   * @generated from field: string cli_client_id = 4;
   */
  cliClientId: string;

  /**
   * @generated from field: repeated string scopes = 5;
   */
  scopes: string[];

  constructor(data?: PartialMessage<OIDCConfig>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "admiral.settings.v1.OIDCConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OIDCConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OIDCConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OIDCConfig;

  static equals(a: OIDCConfig | PlainMessage<OIDCConfig> | undefined, b: OIDCConfig | PlainMessage<OIDCConfig> | undefined): boolean;
}

/**
 * @generated from message admiral.settings.v1.SettingsRequest
 */
export declare class SettingsRequest extends Message<SettingsRequest> {
  constructor(data?: PartialMessage<SettingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "admiral.settings.v1.SettingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingsRequest;

  static equals(a: SettingsRequest | PlainMessage<SettingsRequest> | undefined, b: SettingsRequest | PlainMessage<SettingsRequest> | undefined): boolean;
}

/**
 * @generated from message admiral.settings.v1.SettingsResponse
 */
export declare class SettingsResponse extends Message<SettingsResponse> {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: admiral.settings.v1.OIDCConfig oidc_config = 2;
   */
  oidcConfig?: OIDCConfig;

  constructor(data?: PartialMessage<SettingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "admiral.settings.v1.SettingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingsResponse;

  static equals(a: SettingsResponse | PlainMessage<SettingsResponse> | undefined, b: SettingsResponse | PlainMessage<SettingsResponse> | undefined): boolean;
}

