blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://admiral.io/docs
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/orgs/DataliftHQ/discussions/new/choose
    about: Ask a question or start a discussion about Datalift