// @generated by protoc-gen-es v1.8.0
// @generated from file common/v1/annotations.proto (package admiral.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { Extension } from "@bufbuild/protobuf";
import { FieldOptions, MessageOptions, MethodOptions } from "@bufbuild/protobuf";
import type { Action, Identifier, Reference } from "./schema_pb.js";

/**
 * Use a random high number that won't conflict with annotations from other
 * libraries.
 *
 * @generated from extension: admiral.common.v1.Reference reference = 58901;
 */
export declare const reference: Extension<MessageOptions, Reference>;

/**
 * @generated from extension: admiral.common.v1.Identifier id = 58902;
 */
export declare const id: Extension<MessageOptions, Identifier>;

/**
 * @generated from extension: bool redacted = 58903;
 */
export declare const redacted: Extension<MessageOptions, boolean>;

/**
 * Fields with the log option set to false will be cleared during auditing.
 * Defaults to true.
 *
 * @generated from extension: bool log = 58901;
 */
export declare const log: Extension<FieldOptions, boolean>;

/**
 * Use a random high number that won't conflict with annotations from other
 * libraries.
 *
 * @generated from extension: admiral.common.v1.Action action = 58901;
 */
export declare const action: Extension<MethodOptions, Action>;

/**
 * @generated from extension: bool disable_audit = 58902;
 */
export declare const disable_audit: Extension<MethodOptions, boolean>;

