// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: foo/v1/foo.proto

package foov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FooAPI_GetFoo_FullMethodName = "/admiral.foo.v1.FooAPI/GetFoo"
)

// FooAPIClient is the client API for FooAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FooAPIClient interface {
	GetFoo(ctx context.Context, in *GetFooRequest, opts ...grpc.CallOption) (*GetFooResponse, error)
}

type fooAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewFooAPIClient(cc grpc.ClientConnInterface) FooAPIClient {
	return &fooAPIClient{cc}
}

func (c *fooAPIClient) GetFoo(ctx context.Context, in *GetFooRequest, opts ...grpc.CallOption) (*GetFooResponse, error) {
	out := new(GetFooResponse)
	err := c.cc.Invoke(ctx, FooAPI_GetFoo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooAPIServer is the server API for FooAPI service.
// All implementations should embed UnimplementedFooAPIServer
// for forward compatibility
type FooAPIServer interface {
	GetFoo(context.Context, *GetFooRequest) (*GetFooResponse, error)
}

// UnimplementedFooAPIServer should be embedded to have forward compatible implementations.
type UnimplementedFooAPIServer struct {
}

func (UnimplementedFooAPIServer) GetFoo(context.Context, *GetFooRequest) (*GetFooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFoo not implemented")
}

// UnsafeFooAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FooAPIServer will
// result in compilation errors.
type UnsafeFooAPIServer interface {
	mustEmbedUnimplementedFooAPIServer()
}

func RegisterFooAPIServer(s grpc.ServiceRegistrar, srv FooAPIServer) {
	s.RegisterService(&FooAPI_ServiceDesc, srv)
}

func _FooAPI_GetFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooAPIServer).GetFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooAPI_GetFoo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooAPIServer).GetFoo(ctx, req.(*GetFooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FooAPI_ServiceDesc is the grpc.ServiceDesc for FooAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FooAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.foo.v1.FooAPI",
	HandlerType: (*FooAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFoo",
			Handler:    _FooAPI_GetFoo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foo/v1/foo.proto",
}
