// @generated by protoc-gen-es v1.8.0
// @generated from file authz/v1/authz.proto (package admiral.authz.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { ActionType } from "../../common/v1/schema_pb.js";

/**
 * @generated from enum admiral.authz.v1.Decision
 */
export const Decision = /*@__PURE__*/ proto3.makeEnum(
  "admiral.authz.v1.Decision",
  [
    {no: 0, name: "UNSPECIFIED"},
    {no: 1, name: "DENY"},
    {no: 2, name: "ALLOW"},
  ],
);

/**
 * @generated from message admiral.authz.v1.Subject
 */
export const Subject = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.authz.v1.Subject",
  () => [
    { no: 1, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "groups", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message admiral.authz.v1.CheckRequest
 */
export const CheckRequest = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.authz.v1.CheckRequest",
  () => [
    { no: 1, name: "subject", kind: "message", T: Subject },
    { no: 2, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "action_type", kind: "enum", T: proto3.getEnumType(ActionType) },
    { no: 4, name: "resource", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message admiral.authz.v1.CheckResponse
 */
export const CheckResponse = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.authz.v1.CheckResponse",
  () => [
    { no: 1, name: "decision", kind: "enum", T: proto3.getEnumType(Decision) },
  ],
);

