// @generated by protoc-gen-es v1.8.0
// @generated from file meta/v1/meta.proto (package admiral.meta.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message admiral.meta.v1.GetMetaRequest
 */
export const GetMetaRequest = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.meta.v1.GetMetaRequest",
  [],
);

/**
 * @generated from message admiral.meta.v1.GetMetaResponse
 */
export const GetMetaResponse = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.meta.v1.GetMetaResponse",
  () => [
    { no: 1, name: "foo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

