// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: meta/v1/meta.proto

package metav1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetMetaRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMetaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMetaRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMetaRequestMultiError,
// or nil if none found.
func (m *GetMetaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMetaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetMetaRequestMultiError(errors)
	}

	return nil
}

// GetMetaRequestMultiError is an error wrapping multiple validation errors
// returned by GetMetaRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMetaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMetaRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMetaRequestMultiError) AllErrors() []error { return m }

// GetMetaRequestValidationError is the validation error returned by
// GetMetaRequest.Validate if the designated constraints aren't met.
type GetMetaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMetaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMetaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMetaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMetaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMetaRequestValidationError) ErrorName() string { return "GetMetaRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetMetaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMetaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMetaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMetaRequestValidationError{}

// Validate checks the field values on GetMetaResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetMetaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMetaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMetaResponseMultiError, or nil if none found.
func (m *GetMetaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMetaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Foo

	if len(errors) > 0 {
		return GetMetaResponseMultiError(errors)
	}

	return nil
}

// GetMetaResponseMultiError is an error wrapping multiple validation errors
// returned by GetMetaResponse.ValidateAll() if the designated constraints
// aren't met.
type GetMetaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMetaResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMetaResponseMultiError) AllErrors() []error { return m }

// GetMetaResponseValidationError is the validation error returned by
// GetMetaResponse.Validate if the designated constraints aren't met.
type GetMetaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMetaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMetaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMetaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMetaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMetaResponseValidationError) ErrorName() string { return "GetMetaResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetMetaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMetaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMetaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMetaResponseValidationError{}
