version: "3.8"
name: admiral

services:
  postgres:
    container_name: postgresql
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: admiral
      POSTGRES_USER: admiral
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admiral -d admiral']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - admiral-network
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: /usr/bin/nc -v localhost 1025
      interval: 30s
    networks:
      - admiral-network
    ports:
      - 8025:8025
      - 1025:1025

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: admiral
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_PORT: 9090
      KC_HTTPS_PORT: 9443
    command:
      - start-dev
      - --import-realm
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9090' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - admiral-network
    ports:
      - 9090:9090
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    restart: unless-stopped
    depends_on:
      mailpit:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local

networks:
  admiral-network:
    driver: bridge
    name: admiral-network
