// @generated by protoc-gen-es v1.8.0
// @generated from file healthcheck/v1/healthcheck.proto (package admiral.healthcheck.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message admiral.healthcheck.v1.HealthcheckRequest
 */
export const HealthcheckRequest = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.healthcheck.v1.HealthcheckRequest",
  [],
);

/**
 * @generated from message admiral.healthcheck.v1.HealthcheckResponse
 */
export const HealthcheckResponse = /*@__PURE__*/ proto3.makeMessageType(
  "admiral.healthcheck.v1.HealthcheckResponse",
  [],
);

