name: 'Lint Shell Scripts'

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
    paths:
      - '**.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run Shellcheck
        run: ./tools/shellcheck.sh
