name: 'Lint Shell Scripts'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.sh'
      - .github/workflows/shellcheck.yml

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Shellcheck
        run: ./tools/shellcheck.sh
